#!/bin/sh
# Copyright 2024 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# vi: ft=sh

# shellcheck disable=SC1091
[ -f "/usr/libexec/os-helpers-logging" ] && . /usr/libexec/os-helpers-logging
[ -f "/usr/libexec/os-helpers-fs" ] && . /usr/libexec/os-helpers-fs

BALENA_NONENCRYPTED_BOOT_PARTITION_FILES="\
	@@BALENA_IMAGE_FLAG_FILE@@ \
	imx-boot-@@MACHINE@@-sd.bin-flash_evk \
	@@KERNEL_DEVICE_TREES@@ \
	Image.gz \
	bootenv \
"

is_secured() {
	if @@IS_SECURED_CHECK_SKIP@@; then
		warn "SKIPPING SECURE BOOT ENABLED CHECKS - DO NOT USE IN PRODUCTION"
		return 0
	fi
	if ! command -v imx-otp-tool > /dev/null; then
		fail "Required imx-otp-tool not found"
	fi
	imx-otp-tool -q is-secured
	exit_code=$?
	if [ "${exit_code}" -ne 0 ] && [ "${exit_code}" -ne 1 ]; then
		fail "Unexpected error ${exit_code} when checking for secure state"
	fi
	return "${exit_code}"
}

do_skip() {
	if ! is_secured; then
		return 1
	fi
	skip_nonencrypted_boot_files "${1}"
}
