#!/bin/sh

# Copyright 2024 Balena Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Revokes old key slot preventing old OS from booting
#

set -o errexit

# shellcheck source=/dev/null
. /usr/libexec/os-helpers-logging
# shellcheck source=/dev/null
. /usr/libexec/os-helpers-sb

REVOKE_FILE="/mnt/data/balenahup/revoke_index"

if ! is_secured; then
	info "Rollback: Device is not in secure mode, nothing to do"
	exit
fi

if [ ! -f "${REVOKE_FILE}" ]; then
	info "Rollback: No revoke index file, nothing to do"
	exit
fi

. "${REVOKE_FILE}"

if [ -z "${REVOKE_INDEX}" ]; then
	error "Rollback: Slot index file exists but is empty"
	exit 1
fi

warn "Rollback: Revoking key slot ${REVOKE_INDEX} to prevent previously allowed OS to boot"
if ! imx-otp-tool revoke -s "${REVOKE_INDEX}"; then
	fail "Error when revoking key slot ${REVOKE_INDEX}"
fi

rm -rf "${REVOKE_FILE}" && sync -f "$(dirname ${REVOKE_FILE})"
exit 0
